---
line-length: false
emphasis-style: false
no-bare-urls: false
no-inline-html:
  allowed_elements:
  - u
  - img
  - br
no-multiple-blanks: false
code-block-style: false
commands-show-output: false
no-duplicate-heading: false
no-space-in-emphasis: false
no-emphasis-as-heading: false
