---
line-length:
  line_length: 32767
emphasis-style: false
no-inline-html:
  allowed_elements:
  - u
  - img
  - br
no-multiple-blanks: false
code-block-style: false
commands-show-output: false
no-duplicate-heading: false
no-space-in-emphasis: false
